apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-gazelle
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: ph-ee-engine
  repository: file://../ph-ee-engine
  version: 1.13.0-SNAPSHOT

- name: account_mapper
  version: 1.0.0
  repository: "file://../identity-account-mapper/account-mapper"
