apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector-notifications
  labels:
    app: ph-ee-connector-notifications
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: ph-ee-connector-notifications
  template:
    metadata:
      labels:
        app: ph-ee-connector-notifications
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: "ph-ee-connector-notifications"
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        {{- if .Values.resources }}
        {{- include "common.resourceTemplate" . | nindent 8 }}
        {{- end }}
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
        env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: "{{ .Values.springProfilesActive | default "" }}"
          - name: "ZEEBE_BROKER_CONTACTPOINT"
            value: "{{ .Release.Name }}-zeebe-gateway:26500"
          - name: "HOSTCONFIG_HOST"
            value: "{{ .Values.hostconfig.host | default "" }}"
          - name: "HOSTCONFIG_PORT"
            value: "{{ .Values.hostconfig.port | default "" }}"
          - name: "MESSAGEGATEWAYCONFIG_HOST"
            value: "{{ .Values.messageGatewayConfigHost | default "" }}"
          - name: "NOTIFICATION_LOCAL_HOST"
            value: "{{ .Values.notificationLocalHost | default "" }}"
          - name: "NOTIFICATION_SUCCESS_ENABLED"
            value: "{{ .Values.notificationSuccessEnabled | default "false" }}"
          - name: "NOTIFICATION_FAILURE_ENABLED"
            value: "{{ .Values.notificationFailureEnabled | default "false" }}"
          - name: "LOGGING_LEVEL_ROOT"
            value: "{{ .Values.loggingLevelRoot | default "INFO" }}"
        {{- if .Values.extraEnvs }}
          {{- toYaml .Values.extraEnvs | nindent 12 }}
        {{- end }}
        {{- if .Values.envFrom }}
        envFrom: 
          {{- toYaml .Values.envFrom | nindent 12 }}
        {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: 
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}